### ISSUE TITLE
About Rofi config

### ISSUE THREAD

**Issue by annata83** [sahasatvik/dotfiles#1]
Hello @sahasatvik, do you mind if I ask how you structure text in your rofi key setup?

**Comment by sahasatvik** [comment]
Could you be a little more specific? Do you mean the sxhkd keybindings, or maybe the rofi.rasi config?

**Comment by annata83** [comment]
Sure, theres one screenshot about rofi where the title is keys, assuming is the keybindings  of your apps shortcuts I am wondering how you formatted the text in the file you use to read from!
I have a similar method but the text get all messy when cat it to rofi. I like the neet spacing you achieve...
do you mind explaining how to do that?

**Comment by sahasatvik** [comment]
Aha, I found that snippet on [this blog](https://my-take-on.tech/2020/07/03/some-tricks-for-sxhkd-and-bspwm/#show-a-help-menu-using-rofi), can't take credit for that one! I believe the spacing is handled by the `column` command. The nice thing is that it reads directly from the `sxhkdrc` file where the keybindings are defined ([here](https://github.com/sahasatvik/dotfiles/blob/master/sxhkdrc)'s mine, should be self explanatory for the most part).
